basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.showIcon(IconNames.No)
    basic.pause(500)
    basic.showNumber(15)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(500)
    basic.showNumber(10)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(500)
    basic.showNumber(5)
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(500)
    basic.showIcon(IconNames.Confused)
    basic.pause(5000)
    basic.showNumber(15)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(500)
    basic.showNumber(10)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(500)
    basic.showNumber(5)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(1)
    basic.showIcon(IconNames.Yes)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showNumber(15)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.showNumber(10)
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showNumber(5)
    basic.pause(500)
})
